/* CONTENIDO PÚBLICO: desarrollo completo del HTML original, sin revelar la historia narrativa. */
window.PROJECT_DATA = {
  project: {
    title: 'Frost Apocalypse', studio: 'Turtle Games Dev', status: 'En desarrollo',
    tagline: 'Un proyecto indie nicaragüense documentado paso a paso.',
    description: 'Bitácora oficial de producción: prototipos, mapas, modelado, mecánicas, audio, ambientes, teasers y avances de Frost Apocalypse.',
    platform: 'PC / Steam (planificado)', developer: 'Hanzell René Mayorga Calero', engine: 'Unity 3D · URP'
  },
  projectUpdates: [
    { date:'2022-01-01', year:'2022', category:'Preproducción', title:'Inicio del desarrollo', summary:'Comienza el aprendizaje y la preparación del proyecto: programación, modelado 3D, diseño gráfico y planificación del videojuego.', body:'<p>Esta etapa reúne la idea inicial del proyecto, sus referencias visuales, objetivos de producción y el aprendizaje de las herramientas necesarias para crear un juego independiente.</p><p>El desarrollo se plantea como un proceso de experimentación constante, empezando por prototipos sencillos y aumentando progresivamente la calidad de los escenarios, controles y sistemas.</p>', tags:['concepto','preproducción','aprendizaje'] },
    { date:'2023-01-01', year:'2023', category:'Prototipo', title:'Primeros mapas y pruebas con URP', summary:'Se construyen las primeras casas, el mapa inicial, el menú y las pruebas visuales con Unity 3D y el canal de renderizado URP.', body:'<p>Estas son las primeras fases visuales del proyecto. El objetivo era comprobar escala, navegación, iluminación y composición antes de trabajar en escenarios más grandes.</p><div class="media-grid"><figure><img src="./IMG/Captura casas.png" alt="Captura de las primeras casas del mapa" loading="lazy"><figcaption>Captura del mapa inicial</figcaption></figure><figure><img src="./IMG/Captura urp.png" alt="Prueba del mapa con URP" loading="lazy"><figcaption>Mapa inicial con URP</figcaption></figure><figure><img src="./IMG/Captura3.png" alt="Casa creada con ProBuilder" loading="lazy"><figcaption>Casa creada con ProBuilder</figcaption></figure><figure><img src="./IMG/menu11.png" alt="Menú inicial del juego" loading="lazy"><figcaption>Menú inicial</figcaption></figure></div><p>También se realizaron pruebas de modelado de casas y de integración de piezas en el escenario.</p><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Pre-Alpha_5.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Prueba de modelado de casas</span></div><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Pre-Alpha_2.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Video de desarrollo — pre-alpha v_pf_1.3.0</span></div></div>', tags:['unity','urp','mapa','pre-alpha'] },
    { date:'2023-06-01', year:'2023', category:'Arte conceptual', title:'Diseño visual del proyecto', summary:'Se exploran referencias visuales, composición, escenarios y recursos para definir la identidad artística del juego.', body:'<p>El arte conceptual sirve para probar formas, materiales, iluminación y ambientes antes de convertir las ideas en recursos finales dentro del motor.</p><div class="external-gallery mini-gallery"><a href="./assets/images/itch/itch-4.png" target="_blank"><img src="./assets/images/itch/itch-4.png" alt="Arte y escenario de Frost Apocalypse" loading="lazy"><span>Exploración visual 01</span></a><a href="./assets/images/itch/itch-5.png" target="_blank"><img src="./assets/images/itch/itch-5.png" alt="Prueba visual del proyecto" loading="lazy"><span>Exploración visual 02</span></a></div>', tags:['arte','referencias','dirección artística'] },
    { date:'2023-09-01', year:'2023', category:'Mecánicas', title:'Primeras mecánicas y controles', summary:'Se implementan caminar, correr, agacharse, arrastrarse, saltar obstáculos, subir a plataformas y sistemas de combate.', body:'<p>En esta fase se prueban los sistemas de movimiento, el control del personaje, la cámara, las transiciones y la respuesta de las acciones principales.</p><p>Todos estos sistemas se desarrollan como parte del proceso propio de aprendizaje y producción del proyecto.</p><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Pre-Alpha_3.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Primera cinemática de prueba</span></div><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Pre-Alpha_4.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Prueba de mecánicas</span></div>', tags:['mecánicas','controles','cámara','combate'] },
    { date:'2024-01-01', year:'2024', category:'Diseño de niveles', title:'Nuevas zonas y mapas de block mesh', summary:'El mapa se amplía con nuevas zonas para probar recorridos, escalas, coberturas, accesos y distribución del espacio jugable.', body:'<p>En la etapa pre-alpha las zonas se mantienen sencillas para comprobar si funcionan correctamente antes de añadir detalle, materiales y decoración.</p><div class="media-grid"><figure><img src="./IMG/Expancion1.jpg" alt="Expansión de mapa uno" loading="lazy"><figcaption>Expansión de mapa 1</figcaption></figure><figure><img src="./IMG/Expancion2.jpg" alt="Expansión de mapa dos" loading="lazy"><figcaption>Expansión de mapa 2</figcaption></figure></div><div class="media-grid"><figure><img src="./assets/images/itch/itch-6.png" alt="Escenario publicado en itch.io" loading="lazy"><figcaption>Captura adicional de la demo</figcaption></figure><figure><img src="./assets/images/itch/itch-7.png" alt="Zona del prototipo" loading="lazy"><figcaption>Prueba de escenario</figcaption></figure></div><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Pre-Alpha_1.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Primeras zonas en block mesh map</span></div>', tags:['mapa','block mesh','niveles','pre-alpha'] },
    { date:'2024-06-01', year:'2024', category:'Audio', title:'Tema musical del proyecto', summary:'Se trabaja en una pieza musical propia para acompañar la identidad del juego y sus ambientes.', body:'<p>La música se experimenta con guitarra y producción en FL Studio Mobile. Esta etapa sirve para explorar tono, ritmo y atmósfera.</p><div class="audio-card"><img src="./IMG/logofrost.png" alt="Logotipo de Frost Apocalypse" loading="lazy"><div><strong>Tema musical de Frost Apocalypse</strong><audio controls preload="metadata"><source src="./musica.mp3" type="audio/mpeg">Tu navegador no soporta audio.</audio></div></div>', tags:['audio','música','fl studio mobile'] },
    { date:'2024-12-01', year:'2024', category:'Planificación', title:'Plan de demo y publicación', summary:'Se organiza el camino de producción para presentar una demo jugable y continuar con materiales de promoción.', body:'<p>La demo se plantea como una muestra del estado del desarrollo. La fecha definitiva de cada publicación se anunciará cuando el material esté listo y probado.</p><p>El proceso incluye pruebas de jugabilidad, corrección de errores, optimización, preparación de capturas y publicación en plataformas de distribución.</p>', tags:['demo','publicación','planificación'] },
    { date:'2025-01-01', year:'2025', category:'Dirección de arte', title:'Nuevas zonas y mejoras gráficas', summary:'Se exploran bosques, iluminación, clima, vegetación y variaciones de ambiente, incluyendo una versión nocturna.', body:'<p>Esta fase busca mejorar la atmósfera y estudiar cómo la iluminación, la niebla, la vegetación y el contraste afectan la lectura de los escenarios.</p><div class="media-grid"><figure><img src="./IMG/Bosque1.jpg" alt="Bosque del proyecto" loading="lazy"><figcaption>El bosque</figcaption></figure><figure><img src="./IMG/Bosque2.jpg" alt="Segunda vista del bosque" loading="lazy"><figcaption>Exploración del bosque</figcaption></figure><figure><img src="./IMG/Bosque3.jpg" alt="Tercera vista del bosque" loading="lazy"><figcaption>Detalle de ambiente</figcaption></figure><figure><img src="./IMG/Bosque4.jpg" alt="Bosque durante la noche" loading="lazy"><figcaption>El bosque de noche</figcaption></figure></div><div class="media-grid"><figure><img src="./assets/images/itch/itch-8.png" alt="Captura adicional del entorno" loading="lazy"><figcaption>Captura de la demo</figcaption></figure><figure><img src="./assets/images/itch/itch-9.png" alt="Prueba de iluminación del entorno" loading="lazy"><figcaption>Prueba de iluminación</figcaption></figure></div>', tags:['arte','bosque','iluminación','ambiente'] },
    { date:'2025-06-01', year:'2025', category:'Promoción', title:'Teaser trailer del proyecto', summary:'Se producen varias versiones del teaser para probar ritmo, encuadres, edición, sonido y forma de presentar el desarrollo.', body:'<p>Los teasers funcionan como registro audiovisual del avance y como material para compartir el trabajo en redes sociales.</p><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Teaser_v1.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Teaser trailer — versión 1</span></div><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Teaser_v2.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Teaser trailer — versión 2</span></div><div class="media-frame"><video controls preload="metadata"><source src="./IMG/Teaser_v3.mp4" type="video/mp4">Tu navegador no soporta este video.</video><span>Teaser trailer — versión 3</span></div>', tags:['teaser','trailer','edición','promoción'] },
    { date:'2026-09-14', year:'2026', category:'Demo', title:'Frost Apocalypse 1 Demo — Concept', summary:'La primera demo conceptual presenta una mirada al diseño de niveles, la atmósfera, la dirección artística y algunas ideas de mecánicas.', body:'<p>La Concept Demo no representa el juego completo. Es una muestra del rumbo del proyecto y una oportunidad para recibir comentarios sobre la atmósfera, el detalle y las ideas de juego.</p><p><a class="button" href="https://turtle-games-dev.itch.io/frost-apocalypse-1-demo-concept" target="_blank" rel="noopener noreferrer">Abrir la demo en itch.io ↗</a></p><div class="media-grid"><figure><img src="./assets/images/itch/itch-10.png" alt="Captura de la demo conceptual" loading="lazy"></figure><figure><img src="./assets/images/itch/itch-11.png" alt="Captura adicional de la demo" loading="lazy"></figure><figure><img src="./assets/images/itch/itch-12.png" alt="Escenario de la demo" loading="lazy"></figure></div>', tags:['demo','itch.io','feedback'] },
    { date:'2026-09-17', year:'2026', category:'Organización', title:'Portal interactivo de desarrollo', summary:'La bitácora se reorganiza para publicar avances por fecha, filtrar temas, recibir comentarios y mantener todo el proceso en un solo lugar.', body:'<p>El portal reúne el contenido histórico de producción, la galería de la demo, enlaces sociales y nuevas herramientas para mantener actualizada la página.</p>', tags:['portal','comunidad','documentación'] }
  ],
  faq: [
    ['¿Qué es Frost Apocalypse?', 'Es un proyecto de videojuego indie en desarrollo por Turtle Games Dev. Esta página documenta su producción y no revela todavía los detalles de la historia.'],
    ['¿En qué plataformas se está desarrollando?', 'El plan actual contempla PC y Steam. La disponibilidad final se anunciará cuando esté confirmada.'],
    ['¿Qué motor se utiliza?', 'Unity 3D con el canal de renderizado URP.'],
    ['¿Habrá una demo?', 'Ya existe una demo conceptual disponible en itch.io. Puedes encontrar el enlace dentro de la bitácora y en la sección de contenido extra.'],
    ['¿Cómo puedo seguir el progreso?', 'Puedes seguir esta bitácora, la demo en itch.io, Instagram y el canal de YouTube de Turtle Games Dev.'],
    ['¿El proyecto sigue en desarrollo?', 'Sí. Las entradas se actualizarán conforme avancen los prototipos, mapas, mecánicas, arte, audio y pruebas.']
  ]
};
window.COMMENTS_CONFIG = { provider:'local', itchUrl:'https://turtle-games-dev.itch.io/frost-apocalypse-1-demo-concept', providerUrl:'', repo:'', repoId:'', category:'Announcements', categoryId:'' };
if (window.localStorage && localStorage.getItem('frost-project-data')) { try { window.PROJECT_DATA = JSON.parse(localStorage.getItem('frost-project-data')); } catch (error) { console.warn('No se pudo cargar el borrador local.', error); } }
